//Productos
const productos = [
    {familia: "nada" , tipo: "nada", nombre: "nada", precio: 0},
    {familia: "sizeMasa" , tipo: "sizeMasa1", nombre: "Mediana", precio: 1000},
    {familia: "sizeMasa" , tipo: "sizeMasa2", nombre: "Familiar", precio: 2000},
    {familia: "sizeMasa" , tipo: "sizeMasa3", nombre: "Extra Grande", precio: 3000},
    {familia: "tipoMasa" , tipo: "tipoMasa1", nombre: "Delgada", precio: 0},
    {familia: "tipoMasa" , tipo: "tipoMasa2", nombre: "Tradicional", precio: 0},
    {familia: "tipoMasa" , tipo: "tipoMasa3", nombre: "A la Piedra", precio: 300},
    {familia: "tipoSalsa" , tipo: "tipoSalsa1", nombre: "Salsa de Tomates", precio: 500},
    {familia: "tipoSalsa" , tipo: "tipoSalsa2", nombre: "Salsa BBQ", precio: 700},
    {familia: "tipoSalsa" , tipo: "tipoSalsa3", nombre: "Salsa Alfredo", precio: 800},
    {familia: "tipoSalsa" , tipo: "tipoSalsa4", nombre: "Sin Salsa", precio: 0},
    {familia: "cantidadSalsa" , tipo: "cantidadSalsa1", nombre: "Salsa Regular", precio: 0},
    {familia: "cantidadSalsa" , tipo: "cantidadSalsa2", nombre: "Poca Salsa", precio: 0},
    {familia: "cantidadSalsa" , tipo: "cantidadSalsa3", nombre: "Salsa Extra", precio: 400},
    {familia: "cantidadSalsa" , tipo: "cantidadSalsa4", nombre: "Sin Salsa", precio: 0},
    {familia: "queso" , tipo: "queso1", nombre: "Mozzarella Base", precio: 500},
    {familia: "queso" , tipo: "queso2", nombre: "Sin Mozzarella", precio: 0},
    {familia: "queso" , tipo: "queso3", nombre: "Poco Mozzarella", precio: 400},
    {familia: "queso" , tipo: "queso4", nombre: "Mozzarella Extra", precio: 700},
    {familia: "carne" , tipo: "carne1", nombre: "Carne", precio: 1000},
    {familia: "carne" , tipo: "carne2", nombre: "Tocino", precio: 1500},
    {familia: "carne" , tipo: "carne3", nombre: "Salchicha Italiana", precio: 1000},
    {familia: "carne" , tipo: "carne4", nombre: "Pepperoni", precio: 1000},
    {familia: "carne" , tipo: "carne5", nombre: "Pollo", precio: 1000},
    {familia: "carne" , tipo: "carne6", nombre: "Lomito Canadiense", precio: 2000},
    {familia: "vegetal" , tipo: "vegetal1", nombre: "Tomates Cherry", precio: 500},
    {familia: "vegetal" , tipo: "vegetal2", nombre: "Champiñones", precio: 300},
    {familia: "vegetal" , tipo: "vegetal3", nombre: "Maíz", precio: 300},
    {familia: "vegetal" , tipo: "vegetal4", nombre: "Piñas", precio: 400},
    {familia: "vegetal" , tipo: "vegetal5", nombre: "Tomates", precio: 1000},
    {familia: "vegetal" , tipo: "vegetal6", nombre: "Pimientos Verdes", precio: 300},
    {familia: "vegetal" , tipo: "vegetal7", nombre: "Cebollas", precio: 250},
    {familia: "vegetal" , tipo: "vegetal8", nombre: "Aceitunas Negras", precio: 250},
    {familia: "vegetal" , tipo: "vegetal9", nombre: "Pepinillos", precio: 250},
    ]

    let textoVer = ["Tamaño de Pizza :" , "Tipo de Masa :" , "Tipo de Salsa :" , "Cantidad de Salsa :" , "Cantidad de Queso :" , "Tipo de carne : " , "Tipo de vegetales :"]

